# Audit Configuration
# Configuration for the codebase audit tools

audit:
  version: "1.0.0"

  # Structural analysis settings
  structure:
    check_go_conventions: true
    check_naming: true
    check_imports: true
    check_test_organization: true

  # Dependency analysis settings
  dependencies:
    check_unused: true
    check_security: true
    check_versions: true
    update_suggestions: true

  # Code quality settings
  quality:
    run_gofmt: true
    run_govet: true
    run_golangci_lint: true
    check_unused_code: true
    check_complexity: true
    check_coverage: true
    min_coverage_percent: 70
    max_complexity: 15

  # Reporting settings
  reporting:
    generate_markdown: true
    generate_json: true
    include_suggestions: true
    verbose: true

  # Tool settings
  tools:
    golangci_lint:
      config_file: ".golangci.yml"
      timeout: "5m"
    gocyclo:
      max_complexity: 15
    unused:
      check_exported: false
    govulncheck:
      enabled: true

  # Exclusions
  exclude:
    directories:
      - "vendor"
      - ".git"
      - "node_modules"
    files:
      - "*.pb.go"
      - "*_generated.go"
    patterns:
      - "test/fixtures/*"
