# Security Audit Configuration
# This file configures automated security validation and linting rules

# General Configuration
audit:
  name: "Template Generator Security Audit"
  version: "1.0.0"
  description: "Comprehensive security validation for the template generator project"

# Linting Configuration
linting:
  # Severity thresholds
  fail_on_critical: true
  fail_on_high: false
  warn_on_medium: true
  
  # Categories to check (empty means all)
  categories:
    - cryptography
    - authentication
    - sql-injection
    - cors
    - information-leakage
    - security-headers
    - filesystem
    - input-validation
    - transport-security
    - cookies
  
  # File patterns to include
  include_patterns:
    - "**/*.go"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.jsx"
    - "**/*.tsx"
    - "**/*.tmpl"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"
  
  # File patterns to exclude
  exclude_patterns:
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/.git/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/*_test.go"
    - "**/test/**"
    - "**/tests/**"
    - "**/docs/**"
    - "**/examples/**"

# Security Rules Configuration
rules:
  # Insecure Random Generation Rules
  SEC001:
    enabled: true
    severity: critical
    description: "Timestamp-based random generation"
    auto_fix: true
  
  SEC002:
    enabled: true
    severity: high
    description: "Math/rand usage"
    auto_fix: true
  
  SEC003:
    enabled: true
    severity: high
    description: "Predictable random functions"
    auto_fix: true
  
  SEC004:
    enabled: true
    severity: high
    description: "Timestamp-based ID generation"
    auto_fix: true
  
  SEC005:
    enabled: true
    severity: critical
    description: "Predictable temporary file names"
    auto_fix: true
  
  # CORS Security Rules
  SEC010:
    enabled: true
    severity: critical
    description: "CORS null origin"
    auto_fix: true
  
  SEC011:
    enabled: true
    severity: high
    description: "CORS wildcard with credentials"
    auto_fix: true
  
  SEC012:
    enabled: true
    severity: medium
    description: "CORS overly permissive"
    auto_fix: true
  
  # Authentication Security Rules
  SEC020:
    enabled: true
    severity: critical
    description: "JWT none algorithm"
    auto_fix: true
  
  SEC021:
    enabled: true
    severity: high
    description: "Weak JWT secret"
    auto_fix: false
  
  SEC022:
    enabled: true
    severity: high
    description: "Hardcoded secrets"
    auto_fix: false
  
  # SQL Injection Rules
  SEC030:
    enabled: true
    severity: critical
    description: "SQL string concatenation"
    auto_fix: true
  
  SEC031:
    enabled: true
    severity: high
    description: "SQL variable interpolation"
    auto_fix: true
  
  # Information Leakage Rules
  SEC040:
    enabled: true
    severity: medium
    description: "Detailed error messages"
    auto_fix: true
  
  SEC041:
    enabled: true
    severity: medium
    description: "Debug information exposure"
    auto_fix: true
  
  # Security Headers Rules
  SEC050:
    enabled: true
    severity: low
    description: "Missing X-Content-Type-Options"
    auto_fix: true
  
  SEC051:
    enabled: true
    severity: medium
    description: "Insecure HTTP URLs"
    auto_fix: true
  
  # Cookie Security Rules
  SEC060:
    enabled: true
    severity: low
    description: "Insecure cookie configuration"
    auto_fix: true
  
  # Input Validation Rules
  SEC070:
    enabled: true
    severity: medium
    description: "Missing input validation"
    auto_fix: false
  
  # File Operation Security Rules
  SEC080:
    enabled: true
    severity: high
    description: "Unsafe file operations"
    auto_fix: false
  
  SEC081:
    enabled: true
    severity: high
    description: "Directory traversal risk"
    auto_fix: false
  
  # Cryptographic Rules
  SEC090:
    enabled: true
    severity: high
    description: "Weak cryptographic algorithm"
    auto_fix: false
  
  SEC091:
    enabled: true
    severity: high
    description: "Insecure random seed"
    auto_fix: true

# Testing Configuration
testing:
  # Automated security tests to run
  test_suites:
    - name: "TimestampBasedRandomGeneration"
      enabled: true
      critical: true
    - name: "MathRandUsage"
      enabled: true
      critical: true
    - name: "PredictableIDGeneration"
      enabled: true
      critical: true
    - name: "InsecureTempFileNaming"
      enabled: true
      critical: true
    - name: "WeakCryptographicPatterns"
      enabled: true
      critical: false
    - name: "SQLInjectionPatterns"
      enabled: true
      critical: true
    - name: "CORSVulnerabilities"
      enabled: true
      critical: false
    - name: "HardcodedSecrets"
      enabled: true
      critical: false
  
  # Regression prevention tests
  regression_tests:
    - pattern: "time\\.Now\\(\\)\\.UnixNano\\(\\)"
      description: "Timestamp-based random generation"
      critical: true
    - pattern: "math/rand.*security"
      description: "Math/rand in security code"
      critical: true
    - pattern: "\\.tmp\\..*time\\.Now\\(\\)"
      description: "Predictable temporary files"
      critical: true

# Reporting Configuration
reporting:
  # Output formats to generate
  formats:
    - json
    - sarif
    - junit
  
  # Report retention (days)
  retention_days: 30
  
  # Include in reports
  include_summary: true
  include_details: true
  include_suggestions: true
  include_line_content: true
  
  # SARIF configuration for GitHub Security tab
  sarif:
    tool_name: "Security Linter"
    tool_version: "1.0.0"
    include_rules: true
    include_locations: true

# CI/CD Integration
ci_cd:
  # GitHub Actions integration
  github_actions:
    upload_sarif: true
    create_artifacts: true
    comment_on_pr: true
    fail_on_critical: true
    fail_on_high: false
  
  # Other CI systems
  jenkins:
    publish_junit: true
    archive_artifacts: true
  
  gitlab_ci:
    security_dashboard: true
    merge_request_widget: true

# Notification Configuration
notifications:
  # Slack integration (if configured)
  slack:
    enabled: false
    webhook_url: ""
    channel: "#security"
    notify_on_critical: true
    notify_on_high: false
  
  # Email notifications
  email:
    enabled: false
    recipients: []
    notify_on_critical: true
    notify_on_high: false

# Custom Patterns
custom_patterns:
  # Additional security patterns specific to this project
  - id: "CUSTOM001"
    name: "Template Security Pattern"
    pattern: "{{.*password.*}}"
    category: "template-security"
    severity: "medium"
    description: "Password in template variable"
    suggestion: "Use secure template variables for sensitive data"
    enabled: true
  
  - id: "CUSTOM002"
    name: "Insecure Template Function"
    pattern: "{{.*eval.*}}"
    category: "template-security"
    severity: "high"
    description: "Eval function in template"
    suggestion: "Avoid eval functions in templates"
    enabled: true