name: "minimal-test"
description: "A minimal test project"
license: "MIT"
organization: "test-org"
output_path: "./output/generated"

components:
  frontend:
    main_app: false
    home: false
    admin: false
  backend:
    api: true
  mobile:
    android: false
    ios: false
  infrastructure:
    docker: false
    kubernetes: false
    terraform: false

versions:
  node: "20.0.0"
  go: "1.22.0"
