name: "admin-test"
description: "Test admin template generation"
license: "MIT"
organization: "test-org"
output_path: "./output/generated"

components:
  frontend:
    main_app: false
    home: false
    admin: true
  backend:
    api: false
  mobile:
    android: false
    ios: false
  infrastructure:
    docker: false
    kubernetes: false
    terraform: false

versions:
  node: "20.0.0"
  go: "1.22.0"
  nextjs: "15.5.3"
  react: "19.1.0"
