name: "test-project"
description: "A test project for validation"
license: "MIT"
organization: "test-org"
output_path: "./output/generated"

components:
  frontend:
    main_app: true
    home: false
    admin: false
  backend:
    api: true
  mobile:
    android: false
    ios: false
  infrastructure:
    docker: true
    kubernetes: false
    terraform: false

versions:
  node: "20.0.0"
  go: "1.22.0"
  nextjs: "15.5.3"
  react: "18.0.0"
  kotlin: "2.0.0"
  swift: "5.9.0"
